# Reference: https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_imgproc/py_morphological_ops/py_morphological_ops.html

In [1]:
import numpy as np
import cv2
import os
from matplotlib import pyplot as plt

In [2]:
def show(image, file_name_attr=''):
    file_name = '09_{}.png'.format(file_name_attr)
    cv2.imshow(file_name, image)
    
    while(True):
        key = cv2.waitKey(0)
        if key == 27:
            cv2.destroyAllWindows()
            break
        elif key == ord('s'):
            if cv2.imwrite(os.path.join('saved', file_name), image):
                print('Saved Successfully!')
            else:
                print('Unable to Save!')
            cv2.destroyAllWindows()
            break

In [3]:
image = cv2.imread(os.path.join('images', '22.png'), cv2.IMREAD_COLOR)

# Kernel Types

In [4]:
kernel_cross = cv2.getStructuringElement(cv2.MORPH_CROSS, ksize=(7, 7))
kernel_ellipse = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, ksize=(7, 7))
kernel_rect = cv2.getStructuringElement(cv2.MORPH_RECT, ksize=(7, 7))
print('Cross:', kernel_cross, sep='\n')
print('Ellipse:', kernel_ellipse, sep='\n')
print('Rect:', kernel_rect, sep='\n')

Cross:
[[0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [1 1 1 1 1 1 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]]
Ellipse:
[[0 0 0 1 0 0 0]
 [0 1 1 1 1 1 0]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [0 1 1 1 1 1 0]
 [0 0 0 1 0 0 0]]
Rect:
[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]


# Erosion

In [5]:
eroded = cv2.erode(image, kernel_ellipse)
show(eroded, 'eroded')

# Dialate

In [6]:
dilate = cv2.dilate(image, kernel_ellipse)
show(dilate, 'dilated')

# Opening
First Erosion and then Dilation

In [7]:
opened = cv2.morphologyEx(image, cv2.MORPH_OPEN, kernel_ellipse)
show(opened, 'opened')

# Closing
First Dilation and then Erosion

In [8]:
closed = cv2.morphologyEx(image, cv2.MORPH_CLOSE, kernel_ellipse)
show(closed, 'closed')

# Morphological Gradient
Difference between Dilation and Erosion

In [9]:
grad = cv2.morphologyEx(image, cv2.MORPH_GRADIENT, kernel_ellipse)
show(grad, 'grad')